AWSTemplateFormatVersion: '2010-09-09'
Description: >
  CrawlChat SQS-based Crawler Infrastructure (Container Image)

Parameters:
  LambdaImageUri:
    Type: String
    Description: ECR image URI for the Lambda worker (e.g. 123456789012.dkr.ecr.ap-south-1.amazonaws.com/crawlchat-crawl-worker:latest)

Resources:
  CrawlChatCrawlQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: crawlchat-crawl-tasks

  CrawlChatCrawlWorkerRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: crawlchat-crawl-worker-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: crawlchat-crawl-worker-policy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - sqs:ReceiveMessage
                  - sqs:DeleteMessage
                  - sqs:GetQueueAttributes
                Resource: !GetAtt CrawlChatCrawlQueue.Arn
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"
              # Add additional permissions for MongoDB, S3, etc. as needed

  CrawlChatCrawlWorkerFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: crawlchat-crawl-worker
      Role: !GetAtt CrawlChatCrawlWorkerRole.Arn
      PackageType: Image
      Code:
        ImageUri: !Ref LambdaImageUri
      Timeout: 900
      MemorySize: 1024
      Environment:
        Variables:
          CRAWLCHAT_SQS_QUEUE: !Ref CrawlChatCrawlQueue
          AWS_REGION: !Ref AWS::Region
          # Add your other environment variables here

  CrawlChatCrawlWorkerSQSTrigger:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      BatchSize: 1
      EventSourceArn: !GetAtt CrawlChatCrawlQueue.Arn
      FunctionName: !GetAtt CrawlChatCrawlWorkerFunction.Arn
      Enabled: true

Outputs:
  SQSQueueUrl:
    Description: "URL of the crawl task SQS queue"
    Value: !Ref CrawlChatCrawlQueue
  LambdaWorkerFunctionName:
    Description: "Name of the Lambda worker function"
    Value: !Ref CrawlChatCrawlWorkerFunction 