name: Build Lambda Layer

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-layer:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Build Docker image
      run: |
        docker build -f Dockerfile.lambda-layer -t lambda-layer-builder .
    
    - name: Create container and extract layer
      run: |
        CONTAINER_ID=$(docker create lambda-layer-builder)
        docker cp $CONTAINER_ID:/opt/python ./python
        docker rm $CONTAINER_ID
        
        # Create the layer zip file
        zip -r lambda-layer-essential.zip python/
    
    - name: Check layer file
      run: |
        ls -la lambda-layer-essential.zip
        echo "Layer size: $(du -h lambda-layer-essential.zip | cut -f1)"
    
    - name: Upload layer as artifact
      uses: actions/upload-artifact@v4
      with:
        name: lambda-layer-essential
        path: lambda-layer-essential.zip 