name: Deploy CloudFormation Stack

on:
  push:
    branches: [ main ]
    paths:
      - 'infra/crawlchat-crawl-worker.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy CloudFormation stack
        run: |
          aws cloudformation deploy \
            --template-file infra/crawlchat-crawl-worker.yml \
            --stack-name crawlchat-crawl-worker-stack \
            --capabilities CAPABILITY_NAMED_IAM \
            --parameter-overrides LambdaImageUri=${{ secrets.LAMBDA_IMAGE_URI }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ap-south-1 